// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/[project]/[id].tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/doc.tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/LogView.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/[project]/[id].tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/doc.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/LogView.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
